buildscript {
	repositories {
		mavenLocal()
		mavenCentral()
	}
	dependencies {
		classpath group: 'org.mini2Dx', name: 'butler', version: '2.1.0'
	}
}

subprojects {

	apply plugin: 'java-library'

	group = "org.sheepy.vsand"
	version = "0.0.0-SNAPSHOT"

	java {
		sourceCompatibility = JavaVersion.VERSION_25
		targetCompatibility = JavaVersion.VERSION_25
	}

	repositories {
		mavenLocal()
		mavenCentral()
		maven { url "https://central.sonatype.com/repository/maven-snapshots" }
		maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
	}
}
