#!/bin/sh
DIR=${0%/*}/bin
ARGS="-Xms32M -Xmx64M --enable-preview"
#ARGS="-Xms32M -Xmx64M -Xscmx32M -Xshareclasses:cacheDir=sharedClasses,name=VSand,nonfatal" #OpenJ9
(cd $DIR && ./java $ARGS -p ../modules -m org.sheepy.vsand/org.sheepy.vsand.VSandApplicationLauncher $@)
