#!/bin/sh
DIR=${0%/*}/bin
(cd $DIR && ./java -Xms32M -Xmx64M -p ../modules -Xscmx32M -Xshareclasses:cacheDir=sharedClasses,name=VSand,nonfatal -m org.sheepy.vsand/org.sheepy.vsand.VSandApplicationLauncher  $@)
