<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="model" nsURI="org.sheepy.vsand.model" nsPrefix="model">
  <eClassifiers xsi:type="ecore:EClass" name="VSandApplication" eSuperTypes="../../org.sheepy.lily.core.model/model/application.ecore#//Application">
    <eStructuralFeatures xsi:type="ecore:EReference" name="materials" lowerBound="1"
        eType="#//Materials" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" lowerBound="1"
        eType="#//Transformations" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="drawQueue" upperBound="-1"
        eType="#//DrawCommand" containment="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="mainMaterial" eType="#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="secondaryMaterial" eType="#//Material"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nextMode" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="paused" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="forceClear" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="showSleepZones" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="brushSize" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="4"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="boardUpdateTask" eType="ecore:EClass ../../org.sheepy.lily.vulkan.model/model/process.ecore#//CompositeTask"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BoardConstantBuffer" eSuperTypes="../../org.sheepy.lily.vulkan.model/model/resource.ecore#//ConstantBuffer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="currentBoardBuffer" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawConstantBuffer" eSuperTypes="#//BoardConstantBuffer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boardConstantBuffer" eType="#//BoardConstantBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PixelConstantBuffer" eSuperTypes="#//BoardConstantBuffer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="boardConstantBuffer" eType="#//BoardConstantBuffer"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawCommand" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="material" eType="#//Material"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawCircle" eSuperTypes="#//DrawCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawSquare" eSuperTypes="#//DrawCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DrawLine" eSuperTypes="#//DrawCommand">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x1" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y1" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x2" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="y2" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Materials">
    <eStructuralFeatures xsi:type="ecore:EReference" name="materials" upperBound="-1"
        eType="#//Material" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Material">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Basic"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStatic" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Basic"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="density" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Basic"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="runoff" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Basic"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="r" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Color"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="g" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Color"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Color"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="userFriendly" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="UI"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformations">
    <eStructuralFeatures xsi:type="ecore:EReference" name="transformations" upperBound="-1"
        eType="#//ITransformation" containment="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformation" eSuperTypes="#//ITransformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactant" eType="#//Material">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="notify" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catalyst" eType="#//Material">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="notify" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaterialSelectorPanel" eSuperTypes="../../org.sheepy.lily.core.model/model/presentation.ecore#//IPanel">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lineHeight" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="32">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="UI"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryR" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="255">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Primary Color"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryG" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Primary Color"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryB" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Primary Color"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondaryR" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Secondary Color"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondaryG" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="50">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Secondary Color"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="secondaryB" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="255">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyCategory" value="Secondary Color"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MultipleTransformation" eSuperTypes="#//ITransformation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="reactants" lowerBound="1"
        eType="#//MaterialProvider" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="catalysts" lowerBound="1"
        eType="#//MaterialProvider" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MaterialProvider">
    <eStructuralFeatures xsi:type="ecore:EReference" name="materials" upperBound="-1"
        eType="#//Material">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="notify" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filterMode" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyDescription" value="If true, will consider ALL materials EXCEPT this ones."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ITransformation" abstract="true" interface="true">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="probability" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="propagation" unique="false"
        eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EInt"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="isStaticTransformation"
        unique="false" eType="ecore:EDataType ../../org.eclipse.emf.ecore/model/Ecore.ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="propertyDescription" value="If true, ignore the catalyst and react when stop moving"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="target" eType="#//Material">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="notify" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
