#version 450
#extension GL_ARB_separate_shader_objects : enable

#define WIDTH 800
#define HEIGHT 600
#define WORKGROUP_SIZE 32

#define WHITE vec4(1.0, 1.0, 1.0, 1.0)
#define RED vec4(1.0, 0.0, 0.0, 1.0)
#define BLACK vec4(0.0, 0.0, 0.0, 1.0)

layout (local_size_x = WORKGROUP_SIZE, local_size_y = WORKGROUP_SIZE, local_size_z = 1) in;

layout(binding = 0) readonly buffer buf1 {
   int data[];
} lastBoard;

layout(binding = 1) buffer buf2 {
   int data[];
} nextBoard;

void main() {
  uint arrayLocation = WIDTH * gl_GlobalInvocationID.y + gl_GlobalInvocationID.x;
  int countNeighboors = 0;
  
  if(countNeighboors == 3)
  {
  	nextBoard.data[arrayLocation] = 1;
  } else if (countNeighboors != 2)
  {
  	nextBoard.data[arrayLocation] = 0;
  }

  nextBoard.data[arrayLocation] = 0;
}
